name: Build Packages

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: System info
        run: |
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h

      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Build caches
        uses: apoiston/actions@caches
        with:
          config_buildinfo: config/config.buildinfo

      - name: Show total
        working-directory: ./openwrt
        run: |
          du -ch --max-depth=1 \
            build_dir/host \
            staging_dir/host \
            build_dir/toolchain-* \
            staging_dir/toolchain-* \
            build_dir/target-*/linux-* \
            staging_dir/target-* | tail -n 1
      
      - name: Compress caches
        working-directory: ./openwrt
        run: |
          tar -I "zstd -19 -T$(nproc)" -cf openwrt-caches.tar.zst \
              build_dir/host \
              staging_dir/host \
              build_dir/toolchain-* \
              staging_dir/toolchain-* \
              build_dir/target-*/linux-* \
              staging_dir/target-* \
              dl  
          sha256sum openwrt-caches.tar.zst > sha256sum.txt

      - name: Upload caches
        uses: actions/upload-artifact@v4
        with:
          name: caches
          path: |
            ./openwrt/openwrt-caches.tar.zst
            ./openwrt/sha256sum.txt

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2            
          