name: Build caches

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build caches
    runs-on: ubuntu-latest

    steps:
      - name: System info
        run: |
          lsb_release -a
          free -h

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install buildsystem
        run: |
          sudo apt update && sudo apt install -y \
          build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Clone source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git openwrt

      - name: Sync buildinfo
        run: |
          cp config/config.buildinfo openwrt/

      - name: Prepare feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare config
        working-directory: ./openwrt
        run: |
          while IFS= read -r line; do
              [[ -z "$line" ]] && continue
              echo "$line" >> .config
          done < config.buildinfo
          make defconfig

      - name: Prepare sources
        working-directory: ./openwrt
        run: |
          make -j$(nproc) download

      - name: Compile toolchain
        working-directory: ./openwrt
        run: |
          make -j$(nproc) tools/install
          make -j$(nproc) toolchain/install

      - name: Compile linux
        working-directory: ./openwrt
        run: |
          make -j$(nproc) target/linux/compile

      - name: Compress caches
        working-directory: ./openwrt
        run: |
          tar -I "zstd -19 -T$(nproc)" -cf openwrt-caches.tar.zst \
              build_dir \
              staging_dir \
              dl
          sha256sum openwrt-caches.tar.zst > sha256sum.txt

      - name: Upload caches
        uses: actions/upload-artifact@v4
        with:
          name: caches
          path: |
            ./openwrt/openwrt-caches.tar.zst
            ./openwrt/sha256sum.txt
